LÖVE 11.3 update
arthurferrai/love-scene pull request #1
Opened 2020-11-04 18:11 UTC by Veslo5

Changed run loop by LÖVE latest 11.0 run callback.
https://love2d.org/wiki/love.run

2020-11-05 01:04 UTC, arthurferrai requested changes
Please fix the indentation on commented lines

2020-11-05 01:04 UTC, arthurferrai commented on main.lua
> +                Scene[name](a,b,c,d,e,f) -- handle scene event, if any
Please fix the indentation to match the rest of the file

2020-11-05 01:04 UTC, arthurferrai commented on main.lua
> +        Scene.update(dt)
Please fix the indentation to match the rest of the file

2020-11-05 01:04 UTC, arthurferrai commented on main.lua
> +            Scene.draw()
Please fix the indentation to match the rest of the file

2020-11-05 23:27 UTC, merged

2020-11-05 23:27 UTC, arthurferrai commented
thanks for pull request :D

2020-11-06 07:15 UTC, Veslo5 commented
> 
> 
> thanks for pull request :D

Np, thanks for great library! :)